//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipelineDesign.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public string Id { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public string PipelineId { get; set; }
    
        public virtual Pipeline Pipeline { get; set; }
    }
}
