//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipelineDesign.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nodes
    {
        public int Id { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int PipelineId { get; set; }
    
        public virtual Pipelines Pipelines { get; set; }
    }
}
