//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipelineDesign.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pipeline
    {
        public Pipeline()
        {
            this.Node = new HashSet<Node>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Node> Node { get; set; }
    }
}
